### ISSUE TITLE
The widget doesn't work with inline

### ISSUE THREAD

**Issue by dvarrazzo** [jmrivas86/django-json-widget#1]
* django-json-widget version: 0.1.0
* Django version: 1.9.9
* Python version: 2.7
* Operating System: Ubuntu 16:04

### Description

Trying to use the widget on a `TabularInline`, the generated page structure is broken. The "add another record" line gets merged into the widget dom.

Before using the widget:

![json-widget-inline-pre](https://user-images.githubusercontent.com/199429/29372627-961a5bee-82a3-11e7-9ebb-d9b000ce80b7.png)

Using the widget:

![json-widget-inline-post](https://user-images.githubusercontent.com/199429/29372642-a11d326e-82a3-11e7-8071-12c8e1dece6e.png)

### What I Did

The attempt was just to use the widget in the `formfield_overrides` of the inline class, something like:

```python
@admin.register(models.Allocation)
class Allocation(admin.ModelAdmin):

    class AllocationParams(admin.TabularInline):
        formfield_overrides = {
            JSONField: {'widget': JSONEditorWidget},
        }

    inlines = (AllocationParams, )
```

**Comment by jmrivas86** [comment]
This issue was solved in https://github.com/jmrivas86/django-json-widget/pull/5

**Comment by nostalgiaz** [comment]
Are you sure? I have the same problem. This fix allows you to use different json fields on the same page but not different https://docs.djangoproject.com/en/2.1/ref/contrib/admin/#inlinemodeladmin-objects .

**Comment by TimurKhan** [comment]
Yes, I am sure. 
![Untitled-2](https://user-images.githubusercontent.com/22037878/110245082-e3d02380-7f72-11eb-986f-8088d92527d5.jpg)
