### ISSUE TITLE
Is the maintainer around?

### ISSUE THREAD

**Issue by ramonsaraiva** [jmrivas86/django-json-widget#11]
I'm seeing really really old pull requests floating around the repo without any response from the maintainer.

@jmrivas86 hello?

If not, I'm more than willing to fork it and start maintaining it myself. I want to use this in our application but it needs to support Django 2.1, have more flexible styles, etc..

**Comment by jmrivas86** [comment]
Hello @ramonsaraiva 

I've been pretty busy for a while. Just today I solved and mergeado the PR that I had pending. Throughout the week I will create a new version to reflect the changes in pypi and I will also update the travis file.

Thanks for write and enjoy Free Software!

**Comment by jmrivas86** [comment]
Fixed in PR #8

**Comment by ramonsaraiva** [comment]
Awesome, thank you @jmrivas86 :rocket:
