### ISSUE TITLE
Python 2.7 compatibility is broken due to the use of super() without any argument

### ISSUE THREAD

**Issue by avoiney** [jmrivas86/django-json-widget#15]
* django-json-widget version: 0.2.0
* Django version: 1.11
* Python version: 2.7
* Operating System: Debian 4.18.10-2

### Description

Hello,

I just run the new 0.2.0 version on my django 1.11 and python2.7 project

Thanks

### What I Did

The 0.2.0 version breaks the python2 compatibility because of the use of `super()` without class and instance arguments.

```
  File "/usr/local/lib/python2.7/site-packages/django/forms/fields.py", line 228, in __init__
    super(CharField, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/forms/fields.py", line 96, in __init__
    widget = widget()
  File "/usr/local/lib/python2.7/site-packages/django_json_widget/widgets.py", line 20, in __init__
    super().__init__(attrs=attrs)
TypeError: Error when calling the metaclass bases
    super() takes at least 1 argument (0 given)
ERROR: Job failed: exit code 1
```

**Comment by ramonsaraiva** [comment]
Same issue here.

**Comment by jmrivas86** [comment]
Solved with PR https://github.com/jmrivas86/django-json-widget/pull/16

**Comment by barseghyanartur** [comment]
@jmrivas86:

What about new PyPI release?

**Comment by lisza** [comment]
Same problem here, when pip installing.
