### ISSUE TITLE
New release needed

### ISSUE THREAD

**Issue by dgrant** [jmrivas86/django-json-widget#24]
Can you deploy a new version to PyPyi?

**Comment by ramonsaraiva** [comment]
.. and bump the current version in https://github.com/jmrivas86/django-json-widget/blob/master/django_json_widget/__init__.py

**Comment by docwhite** [comment]
That would be amazing... Thanks.

**Comment by imkaka** [comment]
Can we proceed with this merge?

**Comment by dcalde** [comment]
+1
I would like to able to use features in master (e.g. specify width/height)

**Comment by jmrivas86** [comment]
I have good news, I just published the 1.0.0 version, the first Stable version ! 🎉 🐍
