### ISSUE TITLE
Multiple JSON fields on one model, last overrides all (!!!)

### ISSUE THREAD

**Issue by matiasherranz** [jmrivas86/django-json-widget#3]
* django-json-widget version: 0.1.0
* Django version: 1.10.1
* Python version: 2.7
* Operating System: Mac OS X, Sierra and High Sierra (tested on both)

### Description

- Consider a model with 3 different JSON fields,
- Set the admin for this model to use this package as explained on the docs,
- Go to the Django admin interface for this model,
- The JSONs render OK,
- Edit the last JSON,
- Save,
- The values set for the last of the 3 JSON fields were saved to all 3 JSON fields, overwriting the contents of the other 2.

### What I Did

This is a critical issue for us and made us lose some data. We stopped using the library.

**Comment by xrmx** [comment]
I think this is a dup of #1 and easily fixed by passing something unique as name for the widget template context instead of the field name.

**Comment by k-nut** [comment]
I just ran into the same issue. @xrmx can you elaborate a bit on your idea how to fix this? Is this something that would need to be done in this library or in the project that is using it?

**Comment by xrmx** [comment]
If you looks at the widget template you'll see that the name variable which is passed by the widgets render function is used as id, so you really need to make sure something unique is passed there if you have multiple instances in the same page.
