### ISSUE TITLE
dark mod support 

### ISSUE THREAD

**Issue by elonzh** [jmrivas86/django-json-widget#61]
* django-json-widget version: 1.1.1
* Django version: 3.2
* Python version: 3.8

### Description

Django admin added [theming support](https://docs.djangoproject.com/en/3.2/ref/contrib/admin/#theming-support) since 3.2 and django-json-widget is not readable when the dark mode is enabled.

[jsoneditor/06_custom_styling.html at develop · josdejong/jsoneditor](https://github.com/josdejong/jsoneditor/blob/develop/examples/06_custom_styling.html)

**Comment by jmrivas86** [comment]
Fixed in new 2.0.0 version
