### ISSUE TITLE
Add additional maintainers

### ISSUE THREAD

**Issue by thclark** [jmrivas86/django-json-widget#72]
* django-json-widget version: n/a
* Django version: n/a
* Python version: n/a
* Operating System: n/a

### Description

Hi @jmrivas86 - I've noticed that there are a lot of outstanding pull requests, including one which fixes a security vulnerability.

I understand that it's difficult to stay on top of maintaining all your OSS libraries, but I would be willing to help either do that or have someone from my team help out if you're willing to let us.

Perhaps we could have a discussion and you could add me as a maintainer to help get these issues fixed? An alternative would be transferring the entire repository to jazzband where the community can contribute to it; I could help with that too if you want.

Are you interested?

**Comment by StevenMapes** [comment]
Did you add @thclark @jmrivas86? To help out I've reviewed the following PRs

https://github.com/jmrivas86/django-json-widget/pull/56
https://github.com/jmrivas86/django-json-widget/pull/64
https://github.com/jmrivas86/django-json-widget/pull/65
https://github.com/jmrivas86/django-json-widget/pull/70

Which include an important security update as well as updates in compatibility for Django up to 3.2 along with Python up to 3.9

Once merged this will then allow the project to be better tested and updated to with support for Django 4.0 and 4.1 along with preparing it for Django 4.2

**Comment by StevenMapes** [comment]
I should have noted that I am interested in helping maintain the project

**Comment by jmrivas86** [comment]
PRs done!
