### ISSUE TITLE
Security vulnerability in the `future` dependency

### ISSUE THREAD

**Issue by romanek-adam-b2c2** [jmrivas86/django-json-widget#75]
* django-json-widget version: 1.1.1
* Django version: 3.2
* Python version: 3.10
* Operating System: Ubuntu

### Description

This library depends on the `future` package which is [not maintained](https://github.com/PythonCharmers/python-future/pull/610#issuecomment-1364472979), but contains a high-severity vulnerability: https://github.com/advisories/GHSA-v3c5-jqr6-7qm8

Please drop the dependency on this package if possible.

**Comment by ashokdelphia** [comment]
I agree that stopping using `future` is worthwhile (see #65), but I don't think that vulnerability is reachable in practice from how it is used here. The troublesome regular expression is in the cookie-handling part of the library, which I believe isn't invoked at all here.

I think it's worth dropping as part of no longer supporting very old versions of Django and Python, as that will typically involve using libraries that are practically unmaintained.

**Comment by whardeman** [comment]
@ashokdelphia Thank you for your insight on this! I hadn't looked deeply until now and I agree, it's not a showstopper here.

Most folks are probably (like me) just seeing security vulnerability warnings and scrambling to keep their dependencies clean. In our case, future was only used by two dependencies (the other having already dropped it in a recent release, so just needed to upgrade). 

Still hopeful that @jmrivas86 can add a few more folks to help maintain this. It's a good one!

**Comment by kennell** [comment]
@jmrivas86 Can we get this merged please?

**Comment by jmrivas86** [comment]
Fixed in https://github.com/pifantastic/django-json-widget/pull/1
