### ISSUE TITLE
Static files best practice.

### ISSUE THREAD

**Issue by fabiocaccamo** [jmrivas86/django-json-widget#76]
* django-json-widget version: `1.1.1`
* Django version: `4.1.7`
* Python version: `3.11`
* Operating System: `Ubuntu`

### Description

Static files should be moved to a `django_json_widget/` parent directory to avoid possible collisions with other app's static files.

### What I Did

As you can see the other apps static files are contained in a directory named like the app they blong to (the dist directory belong to `django-json-widget`):

<img width="252" alt="Screenshot 2023-03-29 at 17 46 49" src="https://user-images.githubusercontent.com/1035294/228594513-863bde55-b95e-43a8-8dc2-33991e28d8b6.png">

**Comment by jmrivas86** [comment]
Fixed in #70
