### ISSUE TITLE
Version 2.0.0 causes issues with Django 4.x due to missing sourcemaps

### ISSUE THREAD

**Issue by amarsahinovic** [jmrivas86/django-json-widget#83]
* django-json-widget version: 2.0.0
* Django version: 4.0.10
* Python version: 3.10
* Operating System: MacOS

### Description

This [commit](https://github.com/jmrivas86/django-json-widget/commit/f3c28d392601230ff3e80b22b93866a0ee6579ea) reintroduces `//# sourceMappingURL=jsoneditor.map` at the end of jsoneditor.min.js which breaks Django 4.x upgrade. This line was previously removed in #70.

### What I Did

Tried upgrading to version 2.0.0 to resolve sourcemap issue but `collectstatic` still fails while using `ManifestStaticFilesStorage`.

**Comment by jmrivas86** [comment]
Fixed in 2.0.1 version
